// Re-export all UI components
export * from './button';
export * from './card';
export * from './progress';

// Stub exports for remaining components
// These would typically be generated by shadcn/ui

export const Select = ({ children, ...props }: any) => children;
export const SelectTrigger = ({ children, ...props }: any) => <button {...props}>{children}</button>;
export const SelectValue = ({ placeholder }: any) => <span>{placeholder}</span>;
export const SelectContent = ({ children }: any) => <div>{children}</div>;
export const SelectItem = ({ children, value }: any) => <div data-value={value}>{children}</div>;

export const Slider = ({ value, onValueChange, ...props }: any) => (
  <input
    type="range"
    value={value?.[0] || 0}
    onChange={(e) => onValueChange?.([parseInt(e.target.value)])}
    {...props}
  />
);

export const Switch = ({ checked, onCheckedChange, ...props }: any) => (
  <input
    type="checkbox"
    checked={checked}
    onChange={(e) => onCheckedChange?.(e.target.checked)}
    {...props}
  />
);

export const useToast = () => ({
  toast: ({ title, description, variant }: any) => {
    console.log(`[Toast] ${variant || 'info'}: ${title} - ${description}`);
  },
});

export const Toaster = () => null;
